spring:
  profiles:
    active:
      -dev
---
spring:
  profiles: dev
  application:
    name: my-spring-cloud-config-dev
---
spring:
  profiles: test
  application:
    name: my-spring-cloud-config-test